### ISSUE TITLE
Unit tests need a hook to prefill the objects/states DB

### ISSUE THREAD

**Issue by AlCalzone** [ioBroker/testing#14]
https://travis-ci.org/Apollon77/ioBroker.asterisk/jobs/504447452
https://travis-ci.org/Apollon77/ioBroker.tankerkoenig/jobs/504453662#L672

**Comment by paveltsytovich** [comment]
Hi,

How I fill `config.native` before run **onReady** in unit test?  I need test synchronization config.native (from admin web page config data) and iobroker object database.

**Comment by AlCalzone** [comment]
By default the tests take what is defined in io-package.json

**Comment by paveltsytovich** [comment]
> By default the tests take what is defined in io-package.json

It`s not appropriate, because I need test following cases:

* Add new row in my web admin page. It is should be correct synchronization with iobroker database
* Delete row in my web admin page. It is should be correct synchronization with iobroker database
* Change exists row in my web admin page. It is should be correct synchronization with iobroker database
* Receive from low-level device some command by my adapter. It is should be correct change state in iobroker database
* Call from user code **SetState** function. It is should be correct state change in my adapter and send correct command to low-level device

I think that adapter should be create in each test suite  (for example in **describe**->**beforeEach** may be) or is there another way to test my adapter

**Comment by AlCalzone** [comment]
So you want to dynamically change the adapter config before each test?

**Comment by paveltsytovich** [comment]
> So you want to dynamically change the adapter config before each test?

Yes. I need configure my adapter or emit command from low-level device (via mock) before each test.

**Comment by Apollon77** [comment]
Also needed in some cases where default values can not be used for testing ...

**Comment by AlCalzone** [comment]
There is now the property `overwriteAdapterConfig` on the test options object.
