### ISSUE TITLE
Execute the unload event handler at the end of each startup test

### ISSUE THREAD

**Issue by AlCalzone** [ioBroker/testing#15]
https://travis-ci.org/Apollon77/ioBroker.contactid/jobs/504447879

**Comment by Apollon77** [comment]
https://travis-ci.org/Apollon77/ioBroker.sia/jobs/504452931

**Comment by paveltsytovich** [comment]
I have same problem with `SerialPort`. I create fake serial port with following code
`FakeSerialPort.Binding.createPort('/dev/ttyUSB0',{ echo: false, record: true,autoOpen: false });`
and moking real serialport : 
`additionalMockedModules: {
		'serialport': FakeSerialPort
	}`

When I run test, I receive message  _Uncaught Error: Port is locked cannot open_  because FakeSerialPort in use when I first run, but can`t use again in second run (in compact mode). 
I need handler before create my adapter for each time (normal and compact mode). This handler I will use for create fake serial port
