### ISSUE TITLE
changeAdapterConfig not working as expected

### ISSUE THREAD

**Issue by foxriver76** [ioBroker/testing#218]
**Edit: (AlCalzone)**
`changeAdapterConfig` now works in 2.5.4. It only accepts 2 parameters though:
```
await harness.changeAdapterConfig('hm-rpc', obj);
```

---

<details>
<summary>Original issue</summary>

Hi @AlCalzone,

https://github.com/ioBroker/testing/blob/68970f758fa290fb7553ae30ee7267f5d87e8b03/src/tests/integration/lib/harness.ts#L322 is not working as expected, I changed the config via

```javascript
       describe('Test connection', () => {
            it('Should work', () => {
                return new Promise(async resolve => {
                    const harness = getHarness();
                    // change the adapter config
                    const obj = {
                        native: {
                            homematicAddress: '127.0.0.1',
                            homematicPort: 2010
                        }
                    };
                    await harness.changeAdapterConfig('', '', 'hm-rpc', obj);
                    harness.objects.getObject('system.adapter.hm-rpc.0', (err, obj) => {
                        console.log(JSON.stringify(obj))
....
```
In the console.log, the config has not been applied. Also I don't get why it's necessary to specify `appName` and `testDir` if its not used. Currently I have to change my config by the following code:

```javascript
                    harness.objects.getObject('system.adapter.hm-rpc.0', (err, obj) => {
                        obj.native.homematicAddress = '127.0.0.1';
                        obj.native.homematicPort = 2010;
                        harness.objects.setObject(obj._id, obj);
...
```

This works. 

</details>

**Comment by AlCalzone** [comment]
The reason is the following: `changeAdapterConfig` manually edits the `objects.json` before JS-Controller is started. The user tests are only executed after the controller was started, so this change is not effective (JSON already loaded into memory).

I'll need to add another hook or so to do that.

`appName` and `testDir` are probably remains of a refactor and were forgotten.

**Comment by Excodibur** [comment]
@AlCalzone Is there any update on this? :-)

It would be helpful (actually vital) to be able to change the adapter configuration, before starting any tests. Otherwise, as I understand it the adapter is forced to run with the default values provided via io-package.json. Changing default values there to support testing (like configuring it to connect to a mockserver) is really enduser-unfriendly and sometimes not even possible:

**Comment by foxriver76** [comment]
> Changing default values there to support testing

You can find my workaround in the initial post. Please don't change your default values for testing purposes ;-)

**Comment by Excodibur** [comment]
@foxriver76: Damn, missed that one. Thank you very much!

**Comment by AlCalzone** [comment]
Actually... @foxriver76 @foxthefox @Excodibur can you check if the workaround is still necessary in 2.5.4?
We now use `get/setObject` internally in testing.

**Comment by foxthefox** [comment]
it seems working now.

there is some error in the first post (example), the function accepts only 2 parameters, like this
```
await harness.changeAdapterConfig('hm-rpc', obj);
```

**Comment by AlCalzone** [comment]
Thanks for confirming
